// Mock tour catalogue. In a production build this would come from a CMS or API.

import type { PriceRange, Tour } from './types'

export const categories = [
  'All Tours',
  'Island Hopping',
  'Adventure',
  'Cultural',
  'Family',
  'Water Sports',
  'Romantic',
]

export const destinations = [
  'All Destinations',
  'Phi Phi Islands',
  'Phang Nga Bay',
  'Phuket Town',
  'Khao Sok National Park',
  'Chalong Bay',
  'Koh Hae (Coral Island)',
  'Phuket Hillside',
  'Similan Islands',
]

export const durationTypes = ['All Durations', 'Half Day', 'Full Day', 'Evening']

export const priceRanges: PriceRange[] = [
  { label: 'Any Price', min: 0, max: Infinity },
  { label: 'Under $50', min: 0, max: 50 },
  { label: '$50 - $100', min: 50, max: 100 },
  { label: '$100 - $150', min: 100, max: 150 },
  { label: '$150+', min: 150, max: Infinity },
]

export const tours: Tour[] = [
  {
    id: 1,
    slug: 'phi-phi-islands-speedboat-tour',
    title: 'Phi Phi Islands Speedboat Tour',
    category: 'Island Hopping',
    destination: 'Phi Phi Islands',
    durationType: 'Full Day',
    seatsLeft: 4,
    bookedToday: 7,
    tags: ['Best Seller', 'Family', 'Adventure'],
    image: 'https://picsum.photos/seed/phiphi-main/900/650',
    gallery: [
      'https://picsum.photos/seed/phiphi-1/1000/700',
      'https://picsum.photos/seed/phiphi-2/1000/700',
      'https://picsum.photos/seed/phiphi-3/1000/700',
      'https://picsum.photos/seed/phiphi-4/1000/700',
      'https://picsum.photos/seed/phiphi-5/1000/700',
      'https://picsum.photos/seed/phiphi-6/1000/700',
    ],
    price: 89,
    oldPrice: 109,
    duration: 'Full Day (8-9 hours)',
    groupSize: 'Max 25 people',
    departure: 'Hotel pickup, 7:30 AM',
    rating: 4.9,
    reviewsCount: 482,
    highlights: [
      'Maya Bay (The Beach movie location)',
      'Snorkeling at Pileh Lagoon',
      'Monkey Beach wildlife encounter',
      'Bamboo Island white-sand beach',
      'Buffet lunch on board',
    ],
    description:
      'Discover the iconic Phi Phi Islands on this full-day speedboat adventure. Cruise across the turquoise Andaman Sea to Maya Bay, snorkel in vibrant coral gardens, relax on Bamboo Island and spot wild monkeys at Monkey Beach. Perfect for couples, families and adventure seekers who want to see the best of Phuket in one unforgettable day.',
    itinerary: [
      { time: '07:30 AM', title: 'Hotel Pickup', description: 'Comfortable air-conditioned minivan picks you up from your hotel lobby in the Phuket area.' },
      { time: '09:00 AM', title: 'Depart from Pier', description: 'Board our speedboat at Chalong or Rassada Pier and set sail toward the Phi Phi archipelago.' },
      { time: '10:00 AM', title: 'Maya Bay', description: 'Step ashore at the world-famous bay made famous by "The Beach" and enjoy free time for photos and swimming.' },
      { time: '11:30 AM', title: 'Pileh Lagoon Snorkeling', description: 'Snorkel above colorful coral reefs in this stunning emerald lagoon surrounded by limestone cliffs.' },
      { time: '12:30 PM', title: 'Buffet Lunch', description: 'Enjoy a Thai and international buffet lunch at a beachside restaurant on Phi Phi Don.' },
      { time: '02:00 PM', title: 'Monkey Beach', description: 'Visit Monkey Beach to see playful long-tailed macaques in their natural habitat.' },
      { time: '03:00 PM', title: 'Bamboo Island', description: 'Relax on the powder-white sands of Bamboo Island and enjoy more time for swimming and snorkeling.' },
      { time: '05:00 PM', title: 'Return & Hotel Drop-off', description: 'Cruise back to the pier and transfer back to your hotel by minivan.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Speedboat transportation',
      'English-speaking guide',
      'Buffet lunch and snacks',
      'Drinking water and fruit',
      'Snorkeling equipment',
      'National park entrance fees',
      'Insurance',
    ],
    excluded: [
      'Personal expenses',
      'Alcoholic beverages',
      'Camera fee at Maya Bay (if applicable)',
      'Gratuities (optional)',
    ],
    faq: [
      { q: 'Is this tour suitable for non-swimmers?', a: 'Yes, life jackets are provided and snorkeling is optional. Our crew assists guests who are not confident swimmers.' },
      { q: 'What should I bring?', a: 'Swimwear, sunscreen, a towel, sunglasses, and a change of clothes. Lockers are available for valuables.' },
      { q: 'Is hotel pickup included for all areas?', a: 'Pickup is included for hotels in Patong, Karon, Kata, Phuket Town and Rawai. Other areas may incur a small surcharge.' },
      { q: 'Can I cancel or reschedule my booking?', a: 'Free cancellation up to 24 hours before the tour for a full refund.' },
    ],
  },
  {
    id: 2,
    slug: 'james-bond-island-canoe-tour',
    title: 'James Bond Island & Phang Nga Bay by Canoe',
    category: 'Adventure',
    destination: 'Phang Nga Bay',
    durationType: 'Full Day',
    seatsLeft: 6,
    bookedToday: 5,
    tags: ['Adventure', 'Nature'],
    image: 'https://picsum.photos/seed/jamesbond-main/900/650',
    gallery: [
      'https://picsum.photos/seed/jamesbond-1/1000/700',
      'https://picsum.photos/seed/jamesbond-2/1000/700',
      'https://picsum.photos/seed/jamesbond-3/1000/700',
      'https://picsum.photos/seed/jamesbond-4/1000/700',
      'https://picsum.photos/seed/jamesbond-5/1000/700',
    ],
    price: 75,
    oldPrice: 95,
    duration: 'Full Day (9-10 hours)',
    groupSize: 'Max 30 people',
    departure: 'Hotel pickup, 7:00 AM',
    rating: 4.8,
    reviewsCount: 367,
    highlights: [
      'Iconic Khao Phing Kan (James Bond Island)',
      'Sea cave canoeing through hidden lagoons',
      'Muslim fishing village of Koh Panyee',
      'Limestone karsts of Phang Nga Bay',
      'Lunch with a view over the bay',
    ],
    description:
      'Glide through one of Thailand\'s most dramatic landscapes on this Phang Nga Bay tour. Paddle a sea canoe into hidden lagoons surrounded by towering limestone cliffs, visit the famous James Bond Island from "The Man with the Golden Gun", and explore the floating village of Koh Panyee built entirely on stilts over the water.',
    itinerary: [
      { time: '07:00 AM', title: 'Hotel Pickup', description: 'Pickup from your Phuket hotel and transfer to Surakul Pier in a private air-conditioned vehicle.' },
      { time: '08:30 AM', title: 'Boat Departure', description: 'Board a large boat and cruise into Phang Nga Bay, admiring the dramatic limestone karsts.' },
      { time: '09:30 AM', title: 'Sea Cave Canoeing', description: 'Transfer to small canoes paddled by expert local guides through mangrove tunnels and hidden lagoons (hongs).' },
      { time: '11:00 AM', title: 'James Bond Island', description: 'Step ashore at Khao Phing Kan and Koh Tapu, made famous by the 1974 Bond film.' },
      { time: '12:30 PM', title: 'Lunch at Koh Panyee', description: 'Enjoy a Thai seafood lunch at the unique floating fishing village built on stilts.' },
      { time: '02:00 PM', title: 'Free Time', description: 'Explore the village, browse local handicrafts, or relax with bay views.' },
      { time: '03:30 PM', title: 'Return Cruise', description: 'Sail back toward the pier, taking in the sunset colors over the bay.' },
      { time: '05:30 PM', title: 'Hotel Drop-off', description: 'Transfer back to your hotel in Phuket.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Boat and canoe transportation',
      'English-speaking guide',
      'Thai set lunch',
      'Drinking water and fruit',
      'Life jackets',
      'National park fees',
      'Insurance',
    ],
    excluded: [
      'Personal expenses',
      'Alcoholic beverages',
      'Tips for canoe paddlers (recommended)',
    ],
    faq: [
      { q: 'How long is the canoeing portion?', a: 'Canoeing typically lasts 30-45 minutes per cave/lagoon area, paddled by experienced local guides.' },
      { q: 'Is this suitable for children?', a: 'Yes, this tour is family-friendly and suitable for children aged 4 and above.' },
      { q: 'Will I get wet?', a: 'You may get slightly wet during canoeing, but it is generally a calm, gentle experience.' },
    ],
  },
  {
    id: 3,
    slug: 'phuket-city-big-buddha-cultural-tour',
    title: 'Phuket City & Big Buddha Cultural Tour',
    category: 'Cultural',
    destination: 'Phuket Town',
    durationType: 'Half Day',
    seatsLeft: 8,
    bookedToday: 3,
    tags: ['Culture', 'Half Day'],
    image: 'https://picsum.photos/seed/bigbuddha-main/900/650',
    gallery: [
      'https://picsum.photos/seed/bigbuddha-1/1000/700',
      'https://picsum.photos/seed/bigbuddha-2/1000/700',
      'https://picsum.photos/seed/bigbuddha-3/1000/700',
      'https://picsum.photos/seed/bigbuddha-4/1000/700',
    ],
    price: 45,
    oldPrice: null,
    duration: 'Half Day (4-5 hours)',
    groupSize: 'Max 12 people',
    departure: 'Hotel pickup, 8:00 AM or 1:00 PM',
    rating: 4.7,
    reviewsCount: 251,
    highlights: [
      'The Big Buddha viewpoint',
      'Wat Chalong, Phuket\'s most important temple',
      'Old Phuket Town Sino-Portuguese architecture',
      'Local market and street food tasting',
      'Panoramic island viewpoints',
    ],
    description:
      'Step beyond the beaches and discover the cultural heart of Phuket. Visit the magnificent 45-metre marble Big Buddha for sweeping island views, pay respects at the revered Wat Chalong temple, and wander the colorful streets of Old Phuket Town with its charming Sino-Portuguese shophouses, street art and local food stalls.',
    itinerary: [
      { time: '08:00 AM', title: 'Hotel Pickup', description: 'Comfortable minivan pickup from your hotel.' },
      { time: '08:45 AM', title: 'Big Buddha', description: 'Visit the iconic Big Buddha statue on Nakkerd Hill for panoramic views of the island and Chalong Bay.' },
      { time: '10:00 AM', title: 'Wat Chalong Temple', description: 'Explore Phuket\'s largest and most important Buddhist temple, famous for its ornate architecture.' },
      { time: '11:00 AM', title: 'Old Phuket Town', description: 'Stroll through Thalang and Romanee roads to admire colorful Sino-Portuguese buildings and street art.' },
      { time: '12:00 PM', title: 'Local Market Tasting', description: 'Sample local snacks and fresh fruit at a traditional Thai market.' },
      { time: '12:45 PM', title: 'Hotel Drop-off', description: 'Return transfer to your hotel.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Air-conditioned minivan',
      'English-speaking guide',
      'Bottled water',
      'Entrance fees',
      'Insurance',
    ],
    excluded: [
      'Meals (street food tasting at own expense)',
      'Personal expenses',
      'Tips (optional)',
    ],
    faq: [
      { q: 'What should I wear to the temples?', a: 'Modest clothing covering shoulders and knees is required. Sarongs are available to borrow at temple entrances.' },
      { q: 'Is this tour wheelchair accessible?', a: 'The Big Buddha and Wat Chalong have some stairs, but most areas are accessible. Please contact us for specific needs.' },
    ],
  },
  {
    id: 4,
    slug: 'khao-sok-national-park-adventure',
    title: 'Khao Sok National Park & Cheow Lan Lake Adventure',
    category: 'Adventure',
    destination: 'Khao Sok National Park',
    durationType: 'Full Day',
    seatsLeft: 3,
    bookedToday: 4,
    tags: ['Adventure', 'Nature', 'Overnight Option'],
    image: 'https://picsum.photos/seed/khaosok-main/900/650',
    gallery: [
      'https://picsum.photos/seed/khaosok-1/1000/700',
      'https://picsum.photos/seed/khaosok-2/1000/700',
      'https://picsum.photos/seed/khaosok-3/1000/700',
      'https://picsum.photos/seed/khaosok-4/1000/700',
      'https://picsum.photos/seed/khaosok-5/1000/700',
    ],
    price: 119,
    oldPrice: 145,
    duration: 'Full Day (12 hours)',
    groupSize: 'Max 15 people',
    departure: 'Hotel pickup, 6:00 AM',
    rating: 4.9,
    reviewsCount: 198,
    highlights: [
      'Raft house tour on emerald Cheow Lan Lake',
      'Limestone cliffs rising from the water',
      'Jungle trekking and wildlife spotting',
      'Cave exploration',
      'Authentic Thai lunch on a floating raft',
    ],
    description:
      'Escape to one of the oldest rainforests in the world. This action-packed day trip takes you from Phuket to Khao Sok National Park, where you\'ll cruise across the stunning Cheow Lan Lake surrounded by 100-million-year-old limestone karsts, trek through dense jungle in search of wildlife, and enjoy lunch on a floating raft house.',
    itinerary: [
      { time: '06:00 AM', title: 'Hotel Pickup', description: 'Early pickup for the scenic drive to Khao Sok National Park (approx. 2.5 hours).' },
      { time: '08:30 AM', title: 'Arrival & Briefing', description: 'Arrive at the park, meet your local guide and prepare for the lake cruise.' },
      { time: '09:00 AM', title: 'Cheow Lan Lake Boat Tour', description: 'Long-tail boat cruise across the emerald lake, weaving between dramatic limestone towers.' },
      { time: '10:30 AM', title: 'Jungle Trek', description: 'Guided trek through the rainforest to spot gibbons, hornbills and exotic plant life.' },
      { time: '12:00 PM', title: 'Floating Raft Lunch', description: 'Enjoy a Thai lunch on a traditional floating raft house in the middle of the lake.' },
      { time: '01:30 PM', title: 'Cave Visit', description: 'Optional visit to a limestone cave (seasonal, water levels permitting).' },
      { time: '03:00 PM', title: 'Departure', description: 'Begin the journey back toward Phuket.' },
      { time: '05:30 PM', title: 'Hotel Drop-off', description: 'Arrive back at your hotel in the early evening.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Private transportation',
      'English-speaking naturalist guide',
      'Lake boat tour',
      'Lunch on raft house',
      'Drinking water',
      'Park entrance fees',
      'Insurance',
    ],
    excluded: [
      'Personal expenses',
      'Overnight raft house stay (available as add-on)',
      'Alcoholic beverages',
      'Tips (optional)',
    ],
    faq: [
      { q: 'How much walking is involved?', a: 'The jungle trek covers roughly 1-2 km on natural terrain. Comfortable walking shoes are recommended.' },
      { q: 'Can we stay overnight on the lake?', a: 'Yes, we offer an optional raft house overnight upgrade. Contact us for details and pricing.' },
      { q: 'Is the trip suitable for elderly travelers?', a: 'The boat cruise is relaxed and suitable for most ages; the trek is moderate and may not suit those with mobility issues.' },
    ],
  },
  {
    id: 5,
    slug: 'sunset-dinner-cruise',
    title: 'Romantic Sunset Dinner Cruise',
    category: 'Romantic',
    destination: 'Chalong Bay',
    durationType: 'Evening',
    seatsLeft: 10,
    bookedToday: 9,
    tags: ['Romantic', 'Couples', 'Evening'],
    image: 'https://picsum.photos/seed/sunsetcruise-main/900/650',
    gallery: [
      'https://picsum.photos/seed/sunsetcruise-1/1000/700',
      'https://picsum.photos/seed/sunsetcruise-2/1000/700',
      'https://picsum.photos/seed/sunsetcruise-3/1000/700',
      'https://picsum.photos/seed/sunsetcruise-4/1000/700',
    ],
    price: 69,
    oldPrice: null,
    duration: 'Evening (3 hours)',
    groupSize: 'Max 40 people',
    departure: 'Hotel pickup, 5:30 PM',
    rating: 4.8,
    reviewsCount: 312,
    highlights: [
      'Live music on board',
      'International buffet dinner',
      'Sunset views over Chalong Bay',
      'Welcome cocktail',
      'Perfect for couples and special occasions',
    ],
    description:
      'End your day in paradise with an unforgettable sunset cruise along Phuket\'s southern coastline. Sip a welcome cocktail as the sky turns gold, enjoy a generous international buffet dinner with live music, and watch the sun dip below the Andaman Sea from the open deck. Ideal for honeymoons, anniversaries and romantic evenings.',
    itinerary: [
      { time: '05:30 PM', title: 'Hotel Pickup', description: 'Pickup from your hotel and transfer to Ao Chalong Pier.' },
      { time: '06:00 PM', title: 'Boarding & Welcome Drink', description: 'Board the cruise vessel and enjoy a welcome cocktail as we set sail.' },
      { time: '06:30 PM', title: 'Sunset Cruising', description: 'Cruise along the coastline past Koh Hae and Koh Lone as the sun sets.' },
      { time: '07:00 PM', title: 'Dinner Buffet', description: 'Enjoy a generous international and Thai buffet with live acoustic music.' },
      { time: '08:30 PM', title: 'Return to Pier', description: 'Cruise back to Ao Chalong Pier under the stars.' },
      { time: '09:00 PM', title: 'Hotel Drop-off', description: 'Transfer back to your hotel.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Welcome cocktail',
      'International buffet dinner',
      'Live music entertainment',
      'Soft drinks and water',
      'Insurance',
    ],
    excluded: [
      'Alcoholic beverages (available for purchase)',
      'Personal expenses',
      'Tips (optional)',
    ],
    faq: [
      { q: 'Is this suitable for a marriage proposal?', a: 'Absolutely! Let us know in advance and we can help arrange a special setup or cake.' },
      { q: 'What is the dress code?', a: 'Smart casual. A light jacket is recommended as it can be breezy on deck.' },
      { q: 'Are vegetarian options available?', a: 'Yes, the buffet includes vegetarian and vegan options. Please note dietary needs when booking.' },
    ],
  },
  {
    id: 6,
    slug: 'coral-island-snorkeling-day-trip',
    title: 'Coral Island (Koh Hae) Snorkeling Day Trip',
    category: 'Family',
    destination: 'Koh Hae (Coral Island)',
    durationType: 'Half Day',
    seatsLeft: 12,
    bookedToday: 6,
    tags: ['Family', 'Water Sports', 'Half Day'],
    image: 'https://picsum.photos/seed/coralisland-main/900/650',
    gallery: [
      'https://picsum.photos/seed/coralisland-1/1000/700',
      'https://picsum.photos/seed/coralisland-2/1000/700',
      'https://picsum.photos/seed/coralisland-3/1000/700',
      'https://picsum.photos/seed/coralisland-4/1000/700',
    ],
    price: 39,
    oldPrice: 49,
    duration: 'Half Day (4 hours)',
    groupSize: 'Max 30 people',
    departure: 'Hotel pickup, 8:30 AM or 1:00 PM',
    rating: 4.6,
    reviewsCount: 274,
    highlights: [
      'Crystal-clear water snorkeling',
      'Optional water sports (banana boat, parasailing)',
      'White-sand beach relaxation',
      'Great for kids and non-swimmers',
      'Short boat ride from Phuket',
    ],
    description:
      'A perfect half-day escape for families, Coral Island (Koh Hae) is just a 15-minute speedboat ride from Phuket and famous for its calm, crystal-clear waters and vibrant coral reefs. Snorkel right off the beach, relax on soft white sand, or add on exciting water sports like banana boat rides and parasailing.',
    itinerary: [
      { time: '08:30 AM', title: 'Hotel Pickup', description: 'Pickup from your hotel and transfer to Chalong Pier.' },
      { time: '09:30 AM', title: 'Speedboat to Coral Island', description: 'A short, scenic 15-minute speedboat ride to Koh Hae.' },
      { time: '10:00 AM', title: 'Snorkeling & Beach Time', description: 'Free time to snorkel, swim, sunbathe or try optional water sports.' },
      { time: '12:00 PM', title: 'Lunch (own arrangement)', description: 'Beachside restaurants offer a variety of Thai and international food (not included).' },
      { time: '12:30 PM', title: 'Return Boat', description: 'Speedboat back to Chalong Pier.' },
      { time: '01:00 PM', title: 'Hotel Drop-off', description: 'Transfer back to your hotel.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Speedboat transportation',
      'Snorkeling equipment',
      'Beach chairs',
      'Drinking water',
      'Insurance',
    ],
    excluded: [
      'Lunch',
      'Water sports activities (priced individually on the island)',
      'Personal expenses',
    ],
    faq: [
      { q: 'Are water sports included?', a: 'No, but they are available to purchase directly on the island at affordable prices.' },
      { q: 'Is this trip good for young children?', a: 'Yes, the water near the beach is shallow and calm, making it ideal for families with young kids.' },
    ],
  },
  {
    id: 7,
    slug: 'jungle-atv-zipline-adventure',
    title: 'Jungle ATV & Zipline Adventure',
    category: 'Adventure',
    destination: 'Phuket Hillside',
    durationType: 'Half Day',
    seatsLeft: 5,
    bookedToday: 2,
    tags: ['Adventure', 'Adrenaline'],
    image: 'https://picsum.photos/seed/atvzip-main/900/650',
    gallery: [
      'https://picsum.photos/seed/atvzip-1/1000/700',
      'https://picsum.photos/seed/atvzip-2/1000/700',
      'https://picsum.photos/seed/atvzip-3/1000/700',
      'https://picsum.photos/seed/atvzip-4/1000/700',
    ],
    price: 59,
    oldPrice: 75,
    duration: 'Half Day (4 hours)',
    groupSize: 'Max 16 people',
    departure: 'Hotel pickup, 9:00 AM or 1:30 PM',
    rating: 4.7,
    reviewsCount: 156,
    highlights: [
      '12-station zipline through the rainforest canopy',
      'Off-road ATV jungle trail',
      'Stunning viewpoints over Phuket',
      'Professional safety briefing and gear',
      'Great for thrill-seekers',
    ],
    description:
      'Get your adrenaline pumping with a combination of off-road ATV riding through muddy jungle trails and an exhilarating 12-station zipline course soaring above the rainforest canopy. With professional guides and top safety standards, this is one of Phuket\'s most popular adventure activities.',
    itinerary: [
      { time: '09:00 AM', title: 'Hotel Pickup', description: 'Pickup from your hotel and transfer to the adventure park.' },
      { time: '09:45 AM', title: 'Safety Briefing', description: 'Gear up and receive a full safety briefing from our certified instructors.' },
      { time: '10:00 AM', title: 'ATV Jungle Ride', description: 'Ride a single or double ATV along scenic jungle and hillside trails.' },
      { time: '11:15 AM', title: 'Zipline Course', description: 'Soar through the treetops on a 12-station zipline circuit with guides at every platform.' },
      { time: '12:30 PM', title: 'Refreshments', description: 'Enjoy a refreshing drink and snack after your adventure.' },
      { time: '01:00 PM', title: 'Hotel Drop-off', description: 'Return transfer to your hotel.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Safety equipment (helmet, harness, gloves)',
      'Professional guides/instructors',
      'ATV ride (30 minutes)',
      'Zipline course (12 stations)',
      'Bottled water and snack',
      'Insurance',
    ],
    excluded: [
      'Photos/videos package (available for purchase)',
      'Personal expenses',
      'Tips (optional)',
    ],
    faq: [
      { q: 'Is there a weight or age limit?', a: 'Guests must be at least 12 years old and under 120kg for safety reasons.' },
      { q: 'What should I wear?', a: 'Closed-toe shoes, comfortable clothing you don\'t mind getting muddy, and tie back long hair.' },
      { q: 'Is previous experience required?', a: 'No experience is necessary. All activities are guided and beginner-friendly.' },
    ],
  },
  {
    id: 8,
    slug: 'similan-islands-snorkeling-tour',
    title: 'Similan Islands Snorkeling Tour by Speedboat',
    category: 'Island Hopping',
    destination: 'Similan Islands',
    durationType: 'Full Day',
    seatsLeft: 2,
    bookedToday: 8,
    tags: ['Island Hopping', 'Water Sports', 'Seasonal'],
    image: 'https://picsum.photos/seed/similan-main/900/650',
    gallery: [
      'https://picsum.photos/seed/similan-1/1000/700',
      'https://picsum.photos/seed/similan-2/1000/700',
      'https://picsum.photos/seed/similan-3/1000/700',
      'https://picsum.photos/seed/similan-4/1000/700',
      'https://picsum.photos/seed/similan-5/1000/700',
    ],
    price: 135,
    oldPrice: 159,
    duration: 'Full Day (11 hours)',
    groupSize: 'Max 20 people',
    departure: 'Hotel pickup, 6:00 AM',
    rating: 4.9,
    reviewsCount: 143,
    highlights: [
      'Award-winning Similan Islands National Park',
      'Some of the best snorkeling in Thailand',
      'Crystal-clear turquoise water',
      'Granite boulder islands and white beaches',
      'Buffet lunch on board',
    ],
    description:
      'Venture further afield to the Similan Islands, consistently rated among the world\'s top diving and snorkeling destinations. This full-day speedboat tour visits multiple islands with powder-soft beaches, giant granite boulders and exceptionally clear water teeming with tropical fish. Available seasonally from October to May.',
    itinerary: [
      { time: '06:00 AM', title: 'Hotel Pickup', description: 'Early pickup and transfer to the pier in Khao Lak or Phuket (transfer time varies).' },
      { time: '08:00 AM', title: 'Speedboat Departure', description: 'Board the speedboat and head out to the Similan Islands archipelago.' },
      { time: '09:30 AM', title: 'Island Hopping & Snorkeling', description: 'Visit two to three snorkeling spots with abundant marine life and coral.' },
      { time: '12:00 PM', title: 'Buffet Lunch', description: 'Lunch served on board or on a beach, depending on conditions.' },
      { time: '01:30 PM', title: 'Viewpoint Hike', description: 'Optional short hike to the famous "Sail Rock" viewpoint on Koh Similan.' },
      { time: '03:00 PM', title: 'Return Journey', description: 'Speedboat back to the pier.' },
      { time: '05:00 PM', title: 'Hotel Drop-off', description: 'Transfer back to your hotel in the late afternoon.' },
    ],
    included: [
      'Hotel pickup and drop-off',
      'Speedboat transportation',
      'English-speaking guide',
      'Buffet lunch and snacks',
      'Snorkeling equipment',
      'National park entrance fees',
      'Insurance',
    ],
    excluded: [
      'Personal expenses',
      'Alcoholic beverages',
      'Underwater camera rental',
    ],
    faq: [
      { q: 'When is the Similan Islands season?', a: 'The national park is open from mid-October to mid-May. It is closed the rest of the year for environmental protection.' },
      { q: 'Is this a long journey?', a: 'Yes, it is a full day with significant boat travel time, but most guests agree the scenery is worth it.' },
    ],
  },
]

export const getTourBySlug = (slug: string): Tour | undefined =>
  tours.find((tour) => tour.slug === slug)

export const getFeaturedTours = (count = 4): Tour[] => tours.slice(0, count)

export const getRelatedTours = (currentSlug: string, count = 3): Tour[] =>
  tours.filter((tour) => tour.slug !== currentSlug).slice(0, count)
