export const testimonials = [
  {
    id: 1,
    name: 'Sarah Thompson',
    country: 'United Kingdom',
    avatar: 'https://i.pravatar.cc/150?img=5',
    rating: 5,
    tour: 'Phi Phi Islands Speedboat Tour',
    date: 'March 2026',
    text: 'Absolutely the best day of our entire holiday! The guides were so friendly and Maya Bay was breathtaking. Pickup was right on time and the boat felt very safe. Highly recommend booking with Andaman Wave Tours.',
  },
  {
    id: 2,
    name: 'Marco Bianchi',
    country: 'Italy',
    avatar: 'https://i.pravatar.cc/150?img=15',
    rating: 5,
    tour: 'James Bond Island & Phang Nga Bay by Canoe',
    date: 'February 2026',
    text: 'The canoe trip through the sea caves was magical, our paddler was so skilled. Lunch at the floating village was delicious. Everything was well organized from pickup to drop off.',
  },
  {
    id: 3,
    name: 'Emily & James Carter',
    country: 'Australia',
    avatar: 'https://i.pravatar.cc/150?img=32',
    rating: 5,
    tour: 'Romantic Sunset Dinner Cruise',
    date: 'January 2026',
    text: 'We booked this for our anniversary and it was perfect. The staff even arranged a small cake for us without being asked twice. The sunset views were stunning and the food was great.',
  },
  {
    id: 4,
    name: 'Lukas Becker',
    country: 'Germany',
    avatar: 'https://i.pravatar.cc/150?img=8',
    rating: 4,
    tour: 'Jungle ATV & Zipline Adventure',
    date: 'December 2025',
    text: 'Great fun for adrenaline junkies! The ATV trail was muddy and exciting and the zipline had amazing views. Only small downside was waiting a bit for our group, but otherwise excellent.',
  },
  {
    id: 5,
    name: 'Yuki Tanaka',
    country: 'Japan',
    avatar: 'https://i.pravatar.cc/150?img=26',
    rating: 5,
    tour: 'Khao Sok National Park & Cheow Lan Lake Adventure',
    date: 'November 2025',
    text: 'Cheow Lan Lake is one of the most beautiful places I have ever seen. Our guide was knowledgeable about the wildlife and the lunch on the raft house was a highlight. Worth the early start!',
  },
  {
    id: 6,
    name: 'The Nguyen Family',
    country: 'Vietnam',
    avatar: 'https://i.pravatar.cc/150?img=49',
    rating: 5,
    tour: 'Coral Island (Koh Hae) Snorkeling Day Trip',
    date: 'October 2025',
    text: 'Perfect for our kids! The water was so clear and calm, and the staff helped our children feel comfortable snorkeling for the first time. Short boat ride too which was great for little ones.',
  },
  {
    id: 7,
    name: 'Olivia Martin',
    country: 'Canada',
    avatar: 'https://i.pravatar.cc/150?img=23',
    rating: 5,
    tour: 'Phuket City & Big Buddha Cultural Tour',
    date: 'September 2025',
    text: 'Loved learning about the local culture and history. The Big Buddha views were incredible and Old Phuket Town had so much character. Our guide was very knowledgeable and patient with questions.',
  },
  {
    id: 8,
    name: 'Daniel & Priya Shah',
    country: 'India',
    avatar: 'https://i.pravatar.cc/150?img=36',
    rating: 4,
    tour: 'Similan Islands Snorkeling Tour by Speedboat',
    date: 'April 2026',
    text: 'The Similan Islands are stunning, easily the clearest water we have seen. It is a long day so be prepared, but the snorkeling spots were incredible. Would book again.',
  },
]

export const getAverageRating = () => {
  const total = testimonials.reduce((sum, t) => sum + t.rating, 0)
  return (total / testimonials.length).toFixed(1)
}
